# Generated by Django 4.2.6 on 2023-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_friends_friendshiprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="friendshiprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
